"""add admin_activity table and last_login to users

Revision ID: 6211d379e736
Revises: 0bcf7ab68f09
Create Date: 2026-03-18 18:01:54.773708

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6211d379e736'
down_revision: Union[str, None] = '0bcf7ab68f09'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('admin_activity',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('admin_id', sa.Integer(), nullable=False),
    sa.Column('action', sa.String(length=50), nullable=False),
    sa.Column('target_user_id', sa.Integer(), nullable=True),
    sa.Column('detail', sa.Text(), nullable=True),
    sa.Column('performed_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['admin_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_admin_activity_action', 'admin_activity', ['action'], unique=False)
    op.create_index('ix_admin_activity_admin_id', 'admin_activity', ['admin_id'], unique=False)
    op.create_index(op.f('ix_admin_activity_id'), 'admin_activity', ['id'], unique=False)
    op.create_index('ix_admin_activity_performed_at', 'admin_activity', ['performed_at'], unique=False)
    op.create_index(op.f('ix_customer_view_activity_id'), 'customer_view_activity', ['id'], unique=False)
    op.create_index('ix_identity_data_customer_snapshot', 'identity_data', ['customer_id', 'snapshot_id'], unique=False)
    op.create_index(op.f('ix_identity_data_pan'), 'identity_data', ['pan'], unique=False)
    op.drop_index(op.f('idx_main_data_snapshot_bank'), table_name='main_data')
    op.create_index('ix_main_data_customer_snapshot', 'main_data', ['customer_id', 'snapshot_id'], unique=False)
    op.create_index('ix_main_data_occup_status_cd', 'main_data', ['occup_status_cd'], unique=False)
    op.create_index('ix_main_data_rpt_dt', 'main_data', ['rpt_dt'], unique=False)
    op.create_index(op.f('ix_saved_filters_id'), 'saved_filters', ['id'], unique=False)
    op.create_index(op.f('ix_upload_errors_id'), 'upload_errors', ['id'], unique=False)
    op.add_column('users', sa.Column('last_login', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'last_login')
    op.drop_index(op.f('ix_upload_errors_id'), table_name='upload_errors')
    op.drop_index(op.f('ix_saved_filters_id'), table_name='saved_filters')
    op.drop_index('ix_main_data_rpt_dt', table_name='main_data')
    op.drop_index('ix_main_data_occup_status_cd', table_name='main_data')
    op.drop_index('ix_main_data_customer_snapshot', table_name='main_data')
    op.create_index(op.f('idx_main_data_snapshot_bank'), 'main_data', ['snapshot_id', 'bank_type'], unique=False)
    op.drop_index(op.f('ix_identity_data_pan'), table_name='identity_data')
    op.drop_index('ix_identity_data_customer_snapshot', table_name='identity_data')
    op.drop_index(op.f('ix_customer_view_activity_id'), table_name='customer_view_activity')
    op.drop_index('ix_admin_activity_performed_at', table_name='admin_activity')
    op.drop_index(op.f('ix_admin_activity_id'), table_name='admin_activity')
    op.drop_index('ix_admin_activity_admin_id', table_name='admin_activity')
    op.drop_index('ix_admin_activity_action', table_name='admin_activity')
    op.drop_table('admin_activity')
    # ### end Alembic commands ###
