"""add filenames column to upload_history, make legacy columns nullable

Revision ID: 6fb993179a7a
Revises: cdfabfa9de20
Create Date: 2026-03-19 17:56:29.030456

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6fb993179a7a'
down_revision: Union[str, None] = 'cdfabfa9de20'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('upload_history', sa.Column('filenames', sa.Text(), nullable=True))
    op.alter_column('upload_history', 'main_filename',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
    op.alter_column('upload_history', 'identity_filename',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('upload_history', 'identity_filename',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
    op.alter_column('upload_history', 'main_filename',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
    op.drop_column('upload_history', 'filenames')
    # ### end Alembic commands ###
