"""add new columns to main_data and identity_data, create inquiry_data table

Revision ID: cdfabfa9de20
Revises: e8cb9d0403da
Create Date: 2026-03-19 17:42:15.279755

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cdfabfa9de20'
down_revision: Union[str, None] = 'e8cb9d0403da'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('inquiry_data',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('customer_id', sa.String(length=50), nullable=True),
    sa.Column('inq_purp_cd', sa.String(length=10), nullable=True),
    sa.Column('inq_date', sa.String(length=20), nullable=True),
    sa.Column('m_sub_id', sa.String(length=10), nullable=True),
    sa.Column('amount', sa.Text(), nullable=True),
    sa.Column('snapshot_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_inquiry_data_customer_id'), 'inquiry_data', ['customer_id'], unique=False)
    op.create_index('ix_inquiry_data_customer_snapshot', 'inquiry_data', ['customer_id', 'snapshot_id'], unique=False)
    op.create_index(op.f('ix_inquiry_data_id'), 'inquiry_data', ['id'], unique=False)
    op.create_index(op.f('ix_inquiry_data_snapshot_id'), 'inquiry_data', ['snapshot_id'], unique=False)
    op.add_column('identity_data', sa.Column('phone', sa.String(length=20), nullable=True))
    op.add_column('identity_data', sa.Column('email', sa.Text(), nullable=True))
    op.add_column('identity_data', sa.Column('address', sa.Text(), nullable=True))
    op.add_column('identity_data', sa.Column('pincode', sa.String(length=10), nullable=True))
    op.create_index(op.f('ix_identity_data_phone'), 'identity_data', ['phone'], unique=False)
    op.add_column('main_data', sa.Column('credit_score', sa.String(length=10), nullable=True))
    op.add_column('main_data', sa.Column('full_name', sa.Text(), nullable=True))
    op.add_column('main_data', sa.Column('dob', sa.String(length=20), nullable=True))
    op.add_column('main_data', sa.Column('gender', sa.String(length=10), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('main_data', 'gender')
    op.drop_column('main_data', 'dob')
    op.drop_column('main_data', 'full_name')
    op.drop_column('main_data', 'credit_score')
    op.drop_index(op.f('ix_identity_data_phone'), table_name='identity_data')
    op.drop_column('identity_data', 'pincode')
    op.drop_column('identity_data', 'address')
    op.drop_column('identity_data', 'email')
    op.drop_column('identity_data', 'phone')
    op.drop_index(op.f('ix_inquiry_data_snapshot_id'), table_name='inquiry_data')
    op.drop_index(op.f('ix_inquiry_data_id'), table_name='inquiry_data')
    op.drop_index('ix_inquiry_data_customer_snapshot', table_name='inquiry_data')
    op.drop_index(op.f('ix_inquiry_data_customer_id'), table_name='inquiry_data')
    op.drop_table('inquiry_data')
    # ### end Alembic commands ###
