"""add search filter indexes

Revision ID: d0bb8cb3f7b5
Revises: 
Create Date: 2026-03-16 17:37:47.200476

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd0bb8cb3f7b5'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('ix_identity_data_customer_snapshot', 'identity_data', ['customer_id', 'snapshot_id'], unique=False)
    op.create_index(op.f('ix_identity_data_pan'), 'identity_data', ['pan'], unique=False)
    op.create_index('ix_main_data_customer_snapshot', 'main_data', ['customer_id', 'snapshot_id'], unique=False)
    op.create_index('ix_main_data_occup_status_cd', 'main_data', ['occup_status_cd'], unique=False)
    op.create_index('ix_main_data_rpt_dt', 'main_data', ['rpt_dt'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_main_data_rpt_dt', table_name='main_data')
    op.drop_index('ix_main_data_occup_status_cd', table_name='main_data')
    op.drop_index('ix_main_data_customer_snapshot', table_name='main_data')
    op.drop_index(op.f('ix_identity_data_pan'), table_name='identity_data')
    op.drop_index('ix_identity_data_customer_snapshot', table_name='identity_data')
    # ### end Alembic commands ###
