"""add progress tracking columns to upload_history

Revision ID: e8cb9d0403da
Revises: f78a6a4d432e
Create Date: 2026-03-19 11:04:44.465360

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e8cb9d0403da'
down_revision: Union[str, None] = 'f78a6a4d432e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('upload_history', sa.Column('progress_current', sa.Integer(), server_default='0', nullable=False))
    op.add_column('upload_history', sa.Column('progress_total', sa.Integer(), server_default='0', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('upload_history', 'progress_total')
    op.drop_column('upload_history', 'progress_current')
    # ### end Alembic commands ###
